
- name: Install JDK on servers
  hosts: servers
  become: yes
  become_method: sudo
  roles:
    - role: jdk_setup

- name: Install nginx on servers
  hosts: servers
  become: yes
  become_method: sudo
  roles:
    - role: nginx-setup
